name       : gradle
version    : 3.5.0
release    : 7
source     :
    - https://services.gradle.org/distributions/gradle-3.5-src.zip : e8aa089873c333c42c68b912e08ad4061c54a4b8578f6036a0b2e6a9513f0e42
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    mkdir -p $HOME/.m2/conf
    echo "<settings>\n\t<localRepository>${HOME}/.m2/</localRepository>\n</settings>" > $HOME/.m2/conf/settings.xml
    export GRADLE_USER_HOME=$HOME
    export M2_HOME=$HOME/.m2
    ./gradlew --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    install -d $installdir/usr/bin
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -Dm644 $pkgfiles/gradle.desktop $installdir/usr/share/applications/gradle.desktop
