name       : gradle
version    : 6.5.1
release    : 14
source     :
    - https://github.com/gradle/gradle/archive/v6.5.1.tar.gz : 7ce4b92d6a940e82bdd256a7dc6a259d1edb47f7f7b191a6a2d11aeaf169c8a8
    - https://github.com/gradle/gradle-completion/archive/v1.4.1.tar.gz : 5d77f0c739fe983cfa86078a615f43be9be0e3ce05a3a7b70cb813a1ebd1ceef
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development.
networking : yes
builddeps  :
    - gradle
    - git
rundeps    :
    - openjdk-11
setup      : |
    export GRADLE_COMPLETION_VERSION=1.4.1
    tar xf $sources/v$GRADLE_COMPLETION_VERSION.tar.gz

    %patch -p1 < $pkgfiles/use-dumb-terminal-settings-as-backup.patch
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    export GRADLE_USER_HOME=$workdir/.gradle

    gradle --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    install -Dm00755 $pkgfiles/gradle -t $installdir/usr/bin
    rm $installdir/usr/share/gradle/{LICENSE,NOTICE}
    rm $installdir/usr/share/gradle/bin/*.bat
    rm -rf $installdir/usr/share/gradle/init.d

    install -Dm00644 gradle-completion*/gradle-completion.bash -t $installdir/usr/share/bash-completion/completions
    install -Dm00644 gradle-completion*/_gradle -t $installdir/usr/share/zsh/site-functions
