name       : gradle
version    : 3.1.0
release    : 2
source     :
    - https://github.com/gradle/gradle/archive/v3.1.0.tar.gz : a243a05a1c2f1ffad1a48a2e4cf6cfed2bf4cf7f8ae2c9b43d24ddd93206768b
license    : Apache-2.0
component  : programming.tools
summary    : A powerful build system for the JVM
description: A powerful build system for the JVM
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    ./gradlew --no-daemon install -x determineCommitId -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |-
    install -d $installdir/usr/bin
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -Dm644 $pkgfiles/gradle.desktop $installdir/usr/share/applications/gradle.desktop
