name       : gradle
version    : 3.1.0
release    : 1
source     :
    - https://github.com/gradle/gradle/archive/v3.1.0.tar.gz : a243a05a1c2f1ffad1a48a2e4cf6cfed2bf4cf7f8ae2c9b43d24ddd93206768b
license    : Apache-2.0
component  : programming.tools
summary    : A powerful build system for the JVM
description: A powerful build system for the JVM
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    ./gradlew install -x determineCommitId -Pgradle_installPath=buildDir
install    : |
    install -dm755 $installdir/usr/share/gradle
    install -dm755 $installdir/usr/bin
    cp -r buildDir/* $installdir/usr/share/gradle
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -Dm644 buildDir/media/gradle-icon-512x512.png $installdir/usr/share/pixmaps/gradle.png
    install -Dm644 $pkgfiles/gradle.desktop $installdir/usr/share/applications/gradle.desktop