name       : gradle
version    : '4.9'
release    : 8
source     :
    - https://github.com/gradle/gradle/archive/v4.9.0.tar.gz : 773b014b64c1ee6992e94a9be5c8c66bc13b0d3c2eb47dcf11d00a1bf5d4a1a7
    - https://github.com/gradle/gradle-completion/archive/v1.4.1.tar.gz : 5d77f0c739fe983cfa86078a615f43be9be0e3ce05a3a7b70cb813a1ebd1ceef
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development
networking : yes
builddeps  :
    - openjdk-8
    - git
rundeps    :
    - openjdk-8
environment: |
    export GRADLE_COMPLETION_VERSION="1.4.1"

    export HOME=$PWD/.home
    export JAVA_HOME=/usr/lib64/openjdk-8
    export GRADLE_USER_HOME=$HOME/.gradle
    export M2_HOME=$HOME/.m2
build      : |
    mkdir -p $HOME/.m2/conf
    echo "<settings>\n\t<localRepository>${HOME}/.m2/</localRepository>\n</settings>" > $HOME/.m2/conf/settings.xml

    # prep gradle-completion files
    mkdir -p .gradle-completion
    tar xzf $sources/v$GRADLE_COMPLETION_VERSION.tar.gz --strip-components=1 -C .gradle-completion
    
    ./gradlew --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    mkdir -p $installdir/usr/bin
    install -d $installdir/usr/bin
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -m 00644 -D .gradle-completion/gradle-completion.bash $installdir/etc/bash_completion.d/gradle-completion.bash
