name       : gradle
version    : '4.9'
release    : 10
source     :
    - https://github.com/gradle/gradle/archive/v4.9.0.tar.gz : 773b014b64c1ee6992e94a9be5c8c66bc13b0d3c2eb47dcf11d00a1bf5d4a1a7
    - https://github.com/gradle/gradle-completion/archive/v1.4.1.tar.gz : 5d77f0c739fe983cfa86078a615f43be9be0e3ce05a3a7b70cb813a1ebd1ceef
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development.
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
environment: |
    export M2_HOME=$workdir/.m2
setup      : |
    export GRADLE_COMPLETION_VERSION=1.4.1

    mkdir -p $M2_HOME/conf
    echo "<settings><localRepository>$M2_HOME/</localRepository></settings>" > $M2_HOME/conf/settings.xml
    tar xf $sources/v$GRADLE_COMPLETION_VERSION.tar.gz
build      : |
    export GRADLE_USER_HOME=$workdir/.gradle
    ./gradlew --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    install -Dm00755 $pkgfiles/gradle -t $installdir/usr/bin
    rm $installdir/usr/share/gradle/{LICENSE,NOTICE}
    rm $installdir/usr/share/gradle/bin/*.bat
    rm -rf $installdir/usr/share/gradle/init.d

    install -Dm00644 gradle-completion*/gradle-completion.bash -t $installdir/usr/share/bash-completion/completions
    install -Dm00644 gradle-completion*/_gradle -t $installdir/usr/share/zsh/site-functions
