name       : gradle
version    : 3.2.1
release    : 4
source     :
    - https://services.gradle.org/distributions/gradle-3.2.1-src.zip : d79f2c84ec8ccc2d773e7a8f56d1e4efb129043ea84ab3f9a5db5204fe979b6b
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: A powerful build system for the JVM
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    ./gradlew --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |-
    install -d $installdir/usr/bin
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -Dm644 $pkgfiles/gradle.desktop $installdir/usr/share/applications/gradle.desktop
