name       : gradle
version    : '3.30'
release    : 5
source     :
    - https://services.gradle.org/distributions/gradle-3.3-src.zip : aaa71882a05120cad0d92b203f93f06740f2688b38d9c4c4e6ccfe5e1e639a1c
license    : Apache-2.0
component  : programming.java
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    mkdir -p $HOME/.m2/conf
    echo "<settings>\n\t<localRepository>${HOME}/.m2/</localRepository>\n</settings>" > $HOME/.m2/conf/settings.xml
    export GRADLE_USER_HOME=$HOME
    export M2_HOME=$HOME/.m2
    ./gradlew --no-daemon install -PfinalRelease=1 -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    install -d $installdir/usr/bin
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle
    install -Dm644 $pkgfiles/gradle.desktop $installdir/usr/share/applications/gradle.desktop
