name       : gradle
version    : 7.5.1
release    : 23
source     :
    - git|https://github.com/gradle/gradle.git : v7.5.1
    - git|https://github.com/gradle/gradle-completion.git : b042038e3d3b30a6440c121268894234c509ca1c
license    : Apache-2.0
component  : programming.java
homepage   : https://gradle.org/
summary    : A powerful build system for the JVM
description: |
    Gradle is a build tool with a focus on build automation and support for multi-language development. If you are building, testing, publishing, and deploying software on any platform, Gradle offers a flexible model that can support the entire development lifecycle from compiling and packaging code to publishing web sites. Gradle has been designed to support build automation across multiple languages and platforms including Java, Scala, Android, C/C++, and Groovy, and is closely integrated with development tools and continuous integration servers including Eclipse, IntelliJ, and Jenkins.
networking : yes
builddeps  :
    - gradle
    - openjdk-11
rundeps    :
    - openjdk-17
environment: |
    # Currently requires being built with JDK 11
    export JAVA_HOME=/usr/lib64/openjdk-11
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    # patch completion files
    cp -r $sources/gradle-completion.git $workdir
    cd gradle-completion.git
    %patch -p1 < $pkgfiles/ensure-java-home-is-set-for-completion.patch
    %patch -p1 < $pkgfiles/use-gradle-user-home-for-completion-if-set.patch
build      : |
    export GRADLE_USER_HOME="$workdir/.gradle_home"

    ./gradlew install \
        --no-daemon \
        --no-build-cache \
        --parallel \
        --stacktrace \
        -PfinalRelease=true \
        -Pgradle_installPath=$installdir/usr/share/gradle
install    : |
    rm $installdir/usr/share/gradle/{LICENSE,NOTICE,README,bin/*.bat}
    rm -rf $installdir/usr/share/gradle/init.d/

    sed -i "2r $pkgfiles/java-shim.txt" $installdir/usr/share/gradle/bin/gradle
    install -dm 00755 $installdir/usr/bin/
    ln -s /usr/share/gradle/bin/gradle $installdir/usr/bin/gradle

    install -Dm 00644 gradle-completion.git/gradle-completion.bash $installdir/usr/share/bash-completion/completions/gradle
    install -Dm 00644 gradle-completion.git/_gradle -t $installdir/usr/share/zsh/site-functions/
